name: eShop

on:
  workflow_dispatch:
  push: 
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: '7.0.x'

      - name: Restore
        run: dotnet restore
        working-directory: ./src/Web/
      
      - name: Build and Test
        run: dotnet test --configuration release --logger GitHubActions
        working-directory: ./src/Web/
      
      - name: Publish
        run: dotnet publish --configuration release
        working-directory: ./src/Web/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: eshop-artifact
          path: ./src/Web/bin/release/net7.0/publish/